name: benchmakrs
run-name: Python 3.11 benchmarks
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          - {image: 'registry.suse.com/bci/bci-base:15.4', name: 'bci154', python: '3.10'}
          - {image: 'registry.suse.com/bci/bci-base:15.5', name: 'bci155', python: '3.11'}
          - {image: 'registry.opensuse.org/opensuse/tumbleweed:latest', name: 'tw', python: '3.10'}
          - {image: 'registry.opensuse.org/opensuse/tumbleweed:latest', name: 'tw', python: '3.11'}
      fail-fast: false

    container:
      image: ${{ matrix.container.image }}

    steps:
      - run: zypper --non-interactive install --recommends -t pattern devel_basis
      - run: zypper -n install python311 python311-pip python311-devel
        if: ${{ contains(matrix.container.image, 'suse') && matrix.container.python == '3.11' }}
      - run: zypper -n install python310 python310-pip python310-devel
        if: ${{ contains(matrix.container.image, 'suse') && matrix.container.python == '3.10' }}
      - run: python${{ matrix.container.python }} -m pip install pyperformance
      - run: |
          pyperformance run \
            --benchmarks=-sqlalchemy_imperative,-sqlalchemy_declarative \
            --python=/usr/bin/python${{ matrix.container.python }} \
            -o out.json \
            -f

      - name: Archive pyperformance results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.container.name }}-${{ matrix.container.python }}.json
          path: out.json
